### ISSUE TITLE
Cobalt dust not melting in mekanism energized smelter

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/All-the-mods-7-Sky#126]
i have set up the quatruble ore processing line from mekanism. the first steps work fine, but the smelter doesn't accept the dust.

edit: i just noticed, that other smelter/furnaces don't work either. only the tinkers smeltery works. it doesn't make sense that the first steps work, but the melting doesn't.

**Comment by enigmaquip** [comment]
Fixed in 1.0.5

**Comment by sarim** [comment]
@enigmaquip "raw cobalt" to cobalt ingot recipe is still missing.

**Comment by enigmaquip** [comment]
it's not missing though.... that recipe would be handled by tinker's itself and they chose to omit it from the regular furnace. You can only process raw cobalt down to ingots in the blast furnance. Mekanism only parses furnace recipes

**Comment by sarim** [comment]
@enigmaquip I see. Then I have to add it each time I update the modpack :P IMO the recipe should be added for the sake of consistency, all other ex nihilo sourced raw metal can be smelted to ingot, and I don't want to make special pipeline for cobalt.
